server:
  port: 7004

spring:
  cloud:
    gateway:
      routes:
        ## REST CLIENT -> http://localhost:7004/api/patients
        ## API GATEWAY -> http://patient-service:7000/patients
        - id: patient-service-route
          uri: http://patient-service:7000
          predicates:
            - Path = /api/patients/**
          filters:
            - StripPrefix=1
