server:
  port: 7004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## REST CLIENT -> http://localhost:7004/api/patients
                    ## API GATEWAY -> http://patient-service:7000/patients
                    - id: patient-service-route
                      uri: http://patient-service:7000
                      predicates:
                        - Path=/api/patients/**
                      filters:
                        - StripPrefix=1
                        - JwtValidation

                ## REST CLIENT -> http://localhost:7005/auth/login
                ## API GATEWAY -> http://auth-service:7000/login
                    - id: auth-service-route
                      uri:
                        http://auth-service:7005
                      predicates:
                        - Path=/auth/**
                      filters:
                        - StripPrefix=1


