### Create a new Patient
POST http://localhost:7000/patients
Content-Type: application/json

{
  "name": "billing error",
  "email": "bmksj55545@h.com",
  "address": "address",
  "dateOfBirth": "2001-10-04",
  "registeredDate": "2024-04-05"
}

###